
export const ADD_CUSTOMER_START = 'ADD_CUSTOMER_START';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_FAIL = 'ADD_CUSTOMER_FAIL';
export const ADD_CUSTOMER_INIT = 'ADD_CUSTOMER_INIT';

export const REMOVE_CUSTOMER_START = 'REMOVE_CUSTOMER_START';
export const REMOVE_CUSTOMER_SUCCESS = 'REMOVE_CUSTOMER_SUCCESS';
export const REMOVE_CUSTOMER_FAIL = 'REMOVE_CUSTOMER_FAIL';
export const REMOVE_CUSTOMER_INIT = 'REMOVE_CUSTOMER_INIT';

export const EDIT_CUSTOMER_START = 'EDIT_CUSTOMER_START';
export const EDIT_CUSTOMER_SUCCESS ='EDIT_CUSTOMER_SUCCESS';
export const EDIT_CUSTOMER_FAIL = 'EDIT_CUSTOMER_FAIL';
export const EDIT_CUSTOMER_INIT = 'EDIT_CUSTOMER_INIT';

export const FETCH_CUSTOMERS_START = 'FETCH_CUSTOMERS_START';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAIL = 'FETCH_CUSTOMERS_FAIL';

export const EDIT_MULTIPLE_START = 'EDIT_MULTIPLE_START';
export const EDIT_MULTIPLE_SUCCESS ='EDIT_MULTIPLE_SUCCESS';
export const EDIT_MULTIPLE_FAIL = 'EDIT_MULTIPLE_FAIL';
export const EDIT_MULTIPLE_INIT = 'EDIT_MULTIPLE_INIT';

