
export const ADD_CUSTOMER_START = 'ADD_CUSTOMER_START';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_FAIL = 'ADD_CUSTOMER_FAIL';
export const ADD_CUSTOMER_INIT = 'ADD_CUSTOMER_INIT';

export const REMOVE_CUSTOMER_START = 'REMOVE_CUSTOMER_START';
export const REMOVE_CUSTOMER_SUCCESS = 'REMOVE_CUSTOMER_SUCCESS';
export const REMOVE_CUSTOMER_FAIL = 'REMOVE_CUSTOMER_FAIL';
export const REMOVE_CUSTOMER_INIT = 'REMOVE_CUSTOMER_INIT';

export const EDIT_CUSTOMER_START = 'EDIT_CUSTOMER_START';
export const EDIT_CUSTOMER_SUCCESS ='EDIT_CUSTOMER_SUCCESS';
export const EDIT_CUSTOMER_FAIL = 'EDIT_CUSTOMER_FAIL';
export const EDIT_CUSTOMER_INIT = 'EDIT_CUSTOMER_INIT';

export const FETCH_CUSTOMERS_START = 'FETCH_CUSTOMERS_START';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAIL = 'FETCH_CUSTOMERS_FAIL';



export const ADD_ITEM_START = 'ADD_ITEM_START';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';
export const ADD_ITEM_INIT = 'ADD_ITEM_INIT';

export const REMOVE_ITEM_START = 'REMOVE_ITEM_START';
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL';
export const REMOVE_ITEM_INIT = 'REMOVE_ITEM_INIT';

export const EDIT_ITEM_START = 'EDIT_ITEM_START';
export const EDIT_ITEM_SUCCESS ='EDIT_ITEM_SUCCESS';
export const EDIT_ITEM_FAIL = 'EDIT_ITEM_FAIL';
export const EDIT_ITEM_INIT = 'EDIT_ITEM_INIT';

export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL';



export const EDIT_MULTIPLE_START = 'EDIT_MULTIPLE_START';
export const EDIT_MULTIPLE_SUCCESS ='EDIT_MULTIPLE_SUCCESS';
export const EDIT_MULTIPLE_FAIL = 'EDIT_MULTIPLE_FAIL';
export const EDIT_MULTIPLE_INIT = 'EDIT_MULTIPLE_INIT';

